config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :users,only: [:show,:index,:edit,:update] do
    member do
      # フォローとフォロワー一覧ページのルーティング
      get :following, :followers
    end
    # フォロー&アンフォローのためのルーティング
    resource :relationships, only: [:create, :destroy]
  end

  resources :books do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get "search" => "searches#search"
  
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :user_id, presence: true
  validates :book_id, presence: true
  validates :comment, presence: true, length: {in: 2..140 }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.comments.new(comment_params)
    comment.book_id = @book.id
    comment.save
  end

  def destroy
    Comment.find_by(book_id: params[:book_id], id: params[:id]).destroy
    @book = Book.find(params[:book_id])
  end

    private

    def comment_params
      params.require(:comment).permit(:comment)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_count.html.erb
コメント数：<%= book.comments.count %>

app/views/comments/_index.html.erb
<table>
  <% book.comments.each do |comment| %>
    <tr>
      <td>
        <%= link_to user_path(comment.user) do %>
        <%= attachment_image_tag comment.user, :profile_image, format:'jpeg', fallback:'no_image.jpg', size:'40x40' %><br/>
        <%= comment.user.name %>
        <% end %>
      </td>
      <td><%= comment.comment %></td>
      <% if comment.user == current_user %>
      <td><%= link_to 'Destroy', book_comment_path(comment.book.id, comment.id), method: :delete, remote: true, class:"btn btn-danger" %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/comments/create.js.erb
$("#comments_count").html("<%= j(render 'comments/count', book: @book) %>");
$("#book_comment").html("<%= j(render 'comments/index', book: @book) %>");
$("textarea").val('');

app/views/comments/destroy.js.erb
$("#comments_count").html("<%= j(render 'comments/count', book: @book) %>");
$("#book_comment").html("<%= j(render 'comments/index', book: @book) %>");

app/views/comments/new.html.erb
<%= form_with model:[@book, @comment], local: true do |f| %>
  <%= f.text_area :comment, class:"form-control" %><br/>
  <%= f.submit '送信' %>
<% end %>